### ISSUE TITLE
Write Doxygen-style related pages for main topics

### ISSUE THREAD

**Issue by mattiaisgro** [chaotic-society/theoretica#81]
Write Doxygen-style documentation for the following topics:

- [ ] Linear algebra
- [ ] Complex numbers
- [ ] Statistics
- [ ] Automatic differentiation
- [ ] Calculus

The existing documentation should also be reviewed and improved.

**Comment by Fahad-Ali-Khan-ca** [comment]
Hi, I was thinking In order for me to better understand and write better test cases (and eventually move to do some actual contribution) I should start from here.

**Comment by mattiaisgro** [comment]
> Hi, I was thinking In order for me to better understand and write better test cases (and eventually move to do some actual contribution) I should start from here.

Hello Fahad, do you mean that you would write the related pages or you would like to read them eventually? I was waiting to write the related pages because I have to see how to organize them in Doxygen and especially because some parts of the API are probably going to be reviewed before release. In particular, automatic differentiation may change some of its API, but other modules are pretty much final, so they can be written!

**Comment by mattiaisgro** [comment]
@Fahad-Ali-Khan-ca  to get a general overview of the library I suggest that you read this [document](https://github.com/chaotic-society/documents/blob/main/specification/Theoretica_Software_Structure_Specification.pdf), which is partly outdated but contains valuable information. Some parts on Chebyshev's API are slightly different now. I also would like your opinion on the software design choices. Up to now, we used a hybrid paradigm between functional and OOP, with almost no encapsulation and both methods and functions (e.g. `A.det()` and `algebra::det(A)`). Right now I think that a more functional paradigm, with single responsibility for classes is probably better (e.g. you use `algebra::det(A)` because the determinant is not the matrix' responsibility, but you use histogram's `h.mean()` because it is responsible of computing its own mean).

**Comment by Fahad-Ali-Khan-ca** [comment]
Apologies for the confusion. I want to write the Doxygen-style documentation, as I have some experience with Doxygen. This would help me get familiar with the codebase and contribute meaningfully to the documentation, and hopefully, write better test cases down the line.

**Comment by mattiaisgro** [comment]
> Apologies for the confusion. I want to write the Doxygen-style documentation, as I have some experience with Doxygen. This would help me get familiar with the codebase and contribute meaningfully to the documentation, and hopefully, write better test cases down the line.

It would be extremely useful if you have good knowledge of Doxygen syntax for related pages. One problem that I have been trying to solve is to change the left panel in the web version to remove the subpages, because currently the README is used and instead of having one single subpage, each paragraph is listed with its title, clogging the left panel.

If you know how to force it to be only one page (e.g. "Home") it would already be helpful!

**Comment by Fahad-Ali-Khan-ca** [comment]
Hi @mattiaisgro ,

I apologize for the delay in getting back to this. I had been preparing for my midterms and also had a couple of internship interviews recently, which took up more time than I had anticipated. Balancing everything was challenging, and I regret not being able to respond as quickly as I would have liked.

For the Doxygen main page documentation, I wanted to clarify your preference. Do you want to remove the subpages entirely from the web version, or would you like to keep the subpages but just remove the paragraph titles from the README file? See the attached pictures below.

Thanks for your guidance, and I appreciate your patience!

Best,
Fahad
![image](https://github.com/user-attachments/assets/9ecfecab-3898-479d-8cec-21d0dd5090b3)
![image](https://github.com/user-attachments/assets/2d3b76d4-3de0-4f38-99d5-fdb3f7759fe3)

**Comment by mattiaisgro** [comment]
Hey @Fahad-Ali-Khan-ca, nice to hear from you! Don't worry, I fully understand and you should take your time.

The intended behaviour is shown in the first picture, basically there is a main page, but the different paragraphs are not listed as subpages. The new Related pages should be listed below that, grouped together under "Tutorial".
Thank you for your help!
